import type { ActionFunctionArgs, LoaderFunctionArgs } from "@remix-run/node";
import { json, redirect } from "@remix-run/node";
import { Form, useLoaderData } from "@remix-run/react";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "~/components/ui/card";
import { Badge } from "~/components/ui/badge";
import { Button } from "~/components/ui/button";
import { getDemoStoreService } from "~/lib/demo-store.server";
import { getLang } from "~/lib/lang.server";
import { requireUser } from "~/lib/session.server";
import { t } from "~/lib/i18n";

export async function loader(args: LoaderFunctionArgs) {
  const lang = await getLang(args.request);
  const user = await requireUser(args.request);
  const demo = getDemoStoreService();
  const member = await demo.getMemberForUser(user);
  const notifications = member ? await demo.listNotifications({ memberId: member.id }) : [];
  return json({ lang, member, notifications });
}

/**
 * Mark notification as read (demo).
 */
export async function action(args: ActionFunctionArgs) {
  const user = await requireUser(args.request);
  const demo = getDemoStoreService();
  const member = await demo.getMemberForUser(user);
  if (!member) return json({ ok: false }, { status: 400 });

  const form = await args.request.formData();
  const id = form.get("id")?.toString();
  if (!id) return json({ ok: false }, { status: 400 });

  await demo.markNotificationRead({ memberId: member.id, notificationId: id });
  return redirect("/app/notifications");
}

export default function NotificationsPage() {
  const { lang, notifications } = useLoaderData<typeof loader>();

  return (
    <div className="flex flex-col gap-4">
      <div>
        <h1 className="text-2xl font-semibold">{t(lang, "notifications")}</h1>
        <p className="text-sm text-[color:var(--muted)]">Payment · Booking · Photos (demo flow)</p>
      </div>

      <Card>
        <CardHeader>
          <CardTitle>Inbox</CardTitle>
          <CardDescription>Notifications generated by demo store events.</CardDescription>
        </CardHeader>
        <CardContent className="flex flex-col gap-3">
          {notifications.length ? (
            notifications.map((n) => (
              <div
                key={n.id}
                className="flex flex-col gap-2 rounded-xl border border-[color:var(--border)] bg-[color:var(--bg)] p-3 md:flex-row md:items-start md:justify-between"
              >
                <div className="flex flex-col gap-1">
                  <div className="text-sm font-medium">
                    {n.title}{" "}
                    {n.readAt ? (
                      <span className="text-xs font-normal text-[color:var(--muted)]">(read)</span>
                    ) : null}
                  </div>
                  <div className="text-xs text-[color:var(--muted)]">{n.body}</div>
                  <div className="text-[10px] text-[color:var(--muted)]">
                    {n.createdAt.slice(0, 16).replace("T", " ")} · {n.id}
                  </div>
                </div>
                <div className="flex items-center gap-2">
                  <Badge variant="secondary">{n.type}</Badge>
                  <Form method="post">
                    <input type="hidden" name="id" value={n.id} />
                    <Button size="sm" variant="outline" type="submit" disabled={Boolean(n.readAt)}>
                      Mark read
                    </Button>
                  </Form>
                </div>
              </div>
            ))
          ) : (
            <div className="rounded-xl border border-[color:var(--border)] bg-[color:var(--bg)] p-4 text-sm text-[color:var(--muted)]">
              Empty
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  );
}
